export function getStrings(lang, type){
  switch (lang){
 
    default:
      return {
        "Heading & Time"                : "Heading & Time",
        "Date Format"                   : "Date Format",
        "Wed, Jan 31"                   : "Wed, Jan 31",
        "Jan 31, 2018"                  : "Jan 31, 2018",
        "Wed 31 Jan"                    : "Wed 31 Jan",
        "Wednesday Jan 31"              : "Wednesday Jan 31",
        "Wednesday 31"                  : "Wednesday 31",
        "31 Jan 2018"                   : "31 Jan 2018",
        "Battery Bar"                   : "Change Battery Bar to Battery %",
        "Force 24 Hour Time"            : "Force 24 Hour Time",
        "Time Format"                   : "Time Format",
        "12:00 am (only 12 hour time)"  : "12:00 am (only 12 hour time)",
        "Weather"                       : "Weather",
        "Celsius"                       : "Set Temperature units to Celsius",
        "weather scrolling"             : "Disable weather scrolling",
        "location scrolling"             : "Disable location scrolling",
        "Weather Update Interval"       : "Weather Update Interval",
        "Location Update Interval"      : "Location Update Interval", 
        "5 minutes"                     : "5 minutes",
        "15 minutes"                    : "15 minutes",
        "30 minutes"                    : "30 minutes",
        "1 hour"                        : "1 hour",
        "2 hours"                       : "2 hours",
        "WATCH battery"                 : "Decreasing this will use more WATCH battery.",
        "PHONE battery"                 : "Decreasing this will use more PHONE battery.",
        "update time"                   : "Show time of last weather update",
        "fetched time"                  : "Show when weather is fetched",			
        "high low color"                : "Turn off High and Low color",
        "nerds and debugging"           : "These are mostly for information for nerds and debugging.",
        "Separator Bar Color"           : "Separator Bar Color",
        "Image"                         : "Image",
        "None"                          : "None",
        "Rainbow"                       : "Rainbow",
        "Glass"                         : "Glass",
        "Glass Rainbow"                 : "Glass Rainbow",
        "Wood 1"                        : "Wood 1",
        "Wood 2"                        : "Wood 2",
        "Wood 3"                        : "Wood 3",
        "Candy Cane 1"                  : "Candy Cane 1",
        "Candy Cane 2"                  : "Candy Cane 2",
        "Effect"                        : "Effect",
        "Custom Range Colors"           : "Custom Range Colors",
        "Low Color"                     : "Low Color",
        "Medium Color"                  : "Medium Color",
        "High Color"                    : "High Color",
        "Complete Color"                : "Complete Color",
        "Contact Me"                    : "Please don't hesitate to contact me with questions or suggestions; but be sure to let me know which app or watchface you are talking about. This and all my other apps will always be free and Open Source. If you really like my app please consider buying me a coffee (or more likely electronic components that end up in my classroom). Thanks!",
        "Email"                         : "Email",
        "Build Version"                 : "Build Version and Notes (English Only)",
        "Reset Data"                    : "Reset Data",
        "Activities"                    : "Activities",
        "rhr"                           : "Hide Resting Heart Rate"
      }
  }
}